package reporter

import (
	"fmt"
	"strings"

	"github.com/Homeria/MigraGuard/internal/engine"
	"github.com/Homeria/MigraGuard/internal/parser"
)

// MarkdownReporter generates a formatted Markdown string for GitHub PR comments.
type MarkdownReporter struct{}

func NewMarkdownReporter() *MarkdownReporter {
	return &MarkdownReporter{}
}

func (r *MarkdownReporter) Write(results []parser.AnalysisResult, reports []*engine.RiskAnalysisReport) error {
	var sb strings.Builder

	sb.WriteString("## 🛡️ MigraGuard v3.1 Risk Analysis Report\n\n")
	sb.WriteString("This report provides a risk assessment for the proposed database migration based on real-time and historical workload data.\n\n")

	// Summary Table
	sb.WriteString("| Table | Operation | Risk Level | Risk Score | T_ddl | T_block | Peak Conns |\n")
	sb.WriteString("| :--- | :--- | :--- | :---: | :---: | :---: | :---: |\n")

	for i, res := range results {
		report := reports[i]
		riskIcon := "✅"
		if report.RiskLevel == "Danger" {
			riskIcon = "🚨"
		} else if report.RiskLevel == "Warning" {
			riskIcon = "⚠️"
		}

		sb.WriteString(fmt.Sprintf("| `%s` | `%s` | %s %s | %.2f%% | %.2fms | %.2fms | %d |\n",
			res.TableName,
			res.Operation,
			riskIcon,
			report.RiskLevel,
			report.RiskScore,
			report.EstimatedDDLTime,
			report.BlockingTime,
			report.PeakConnections,
		))
	}

	sb.WriteString("\n---\n")

	// Detailed Insights
	sb.WriteString("### 🧠 Analysis Insights\n\n")
	for i, res := range results {
		report := reports[i]
		sb.WriteString(fmt.Sprintf("#### 📦 Table: `%s` (%s)\n", res.TableName, res.Operation))
		
		sb.WriteString(fmt.Sprintf("- **Traffic Context:** Currently running at **%.1f TPS** (Avg 1h: %.1f, Peak 24h: %.1f).\n", 
			report.CurrentTPS, report.AvgTPS1h, report.PeakTPS24h))
		
		if report.SafeWindow != "" {
			sb.WriteString(fmt.Sprintf("- **Safe Window:** Deployment is significantly safer at **%s** (Historical Avg: %.1f TPS).\n", 
				report.SafeWindow, report.SafeWindowTPS))
		}

		if report.PermanentFailure {
			sb.WriteString("- 🚨 **CRITICAL:** High traffic exceeds system throughput during migration. Permanent failure predicted!\n")
		} else if report.RiskLevel == "Danger" {
			sb.WriteString("- 🚨 **WARNING:** Critical connection spike predicted. Consider deploying during the safe window.\n")
		}
		sb.WriteString("\n")
	}

	sb.WriteString("---\n")
	sb.WriteString("*Generated by [MigraGuard](https://github.com/Homeria/MigraGuard) v3.1*")

	fmt.Println(sb.String())
	return nil
}
